version: '3.8'

services:
  frontend:
    build: ./JoggoGamesFrontend
    ports:
      - '8001:8001'
    environment:
      - API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./JoggoGamesBackend
    ports:
      - '8002:8002'
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=${DB_DIALECT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
